@startuml
title Image Upload Process

actor       Dashcam_Owner 
entity      Dashcam_Application
entity      "Website" as Website << AWS Elastic Beanstalk>>
boundary    "Upload Image API" as Image_Upload_API << AWS API Gateway >>
control     "Image Upload Function" as Lambda_Upload_Function << AWS Lambda Function >>
control     "Image Feature Detection" as AWS_Rekognition << AWS Rekognition >>
database    "Image Storage" as AWS_S3 << AWS S3 >>
database    "Image Metadata Storage" as Imgs_AWS_DynamoDB << AWS DynamoDB >>
database    "Events Metadata Storage" as Events_AWS_DynamoDB << AWS DynamoDB >>

Dashcam_Owner -> Dashcam_Application: __**User Interaction:**__\nStart Image Upload
Dashcam_Application -> Image_Upload_API: __**API Request Parameters:**__\n{Image, Latitude, Longitude}
Dashcam_Owner -> Website: __**User Interaction:**__\nStart Image Upload
Website -> Image_Upload_API: __**API Request Parameters:**__\n{Image, Latitude, Longitude}
Image_Upload_API -> Lambda_Upload_Function: __**API Request Parameters:**__\n{Image, Latitude, Longitude}
Lambda_Upload_Function --> AWS_S3: __**Image Storage Request:**__\n{Image}
Lambda_Upload_Function <-- AWS_S3: __**Image Storage Response:**__\n{Image URL}
Lambda_Upload_Function --> AWS_Rekognition: __**Image Detection Initiation:**__\n{Image}
AWS_Rekognition --> AWS_Rekognition: Detect Contents of Image
AWS_Rekognition --> Lambda_Upload_Function: __**Image Detection Response:**__\n{Bounding Box, Features Detected in Image}
Lambda_Upload_Function --> AWS_S3: __**Image Storage Request:**__\n{Image with bounding box}
Lambda_Upload_Function <-- AWS_S3: __**Image Storage Response:**__\n{Image with bounding box URL}
Lambda_Upload_Function --> Imgs_AWS_DynamoDB: __**Image Metadata Database Storage Request:**__\n{Upload Time,\n Original Image URL,\n Labeled Image URL,\n Latitude,\n Longitude,\n [Features Detected in Image]}

' Event querying
Lambda_Upload_Function --> Events_AWS_DynamoDB: __**Event Metadata Database Query For Events Similar to Image:**__\n {GPS Bounding Box,\n Freshness,\n Event Type}
Events_AWS_DynamoDB --> Lambda_Upload_Function: __**Event Metadata Database Response:**__\n List of Events\n{Event Start Time, Event Type,\n Latitude,Longitude,\n Most recent event update time, [Associated Images]}
Lambda_Upload_Function --> Events_AWS_DynamoDB: __**Associate Images to Event or Create new Event Metadata:**__ \n{Uploaded Image Metadata, \nEvent to Associate with Metadata (If found)}

@enduml